name: naplan_ui
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0  # ✅ Add this package

  # UI & State Management
  provider: ^6.1.2       # State management
  flutter_bloc: ^8.1.3   # Bloc pattern

  # UI Components
  cupertino_icons: ^1.0.8  # iOS style icons
  google_fonts: ^4.0.4     # Custom fonts (downgraded for compatibility)
  lottie: ^3.1.0           # Animated illustrations
  flutter_svg: ^2.0.10     # SVG support
  flutter_html: ^3.0.0-beta.2  # Added for HTML rendering in explanation
  photo_view: ^0.14.0     # Added for image zooming and scrolling capabilities

  # Exam & Form Handling
  intl: ^0.18.1            # Date formatting
  shared_preferences: 2.2.2  # Storing user data (downgraded for compatibility)
  timer_count_down: ^2.2.2
  path_provider: ^2.0.15
  flutter_secure_storage: ^9.0.0  # Secure storage for sensitive data
  uuid: ^4.0.0             # UUID generation
  device_info_plus: ^10.1.0  # Device information for persistent UID
  crypto: ^3.0.3           # Cryptographic functions for hashing
  # Networking & APIs
  http: ^1.0.0
  dio: ^5.3.3              # Advanced networking
  webview_flutter: ^4.4.2  # WebView support

  # Audio & Multimedia
  just_audio: ^0.9.37      # Downgraded to be compatible with Dart SDK 3.2.0
  flutter_tts: ^3.8.3      # Downgraded to be compatible with Dart SDK 3.2.0
  flutter_math_fork: ^0.7.4
  audio_video_progress_bar: ^2.0.3
  flutter_pdfview: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/data/questions.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

